---
title: "Unterbrechungsintention"
output:
  html_document:
    toc: yes
---
```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r daten}

# allgemein
library(ggplot2)
library(foreign)
library(Hmisc)
library(car)
library(plyr)
library(dplyr)
library(magrittr)
library(scales)

# Kreuztabellen
library(gmodels)

# working directory
setwd("/Users/thomask/Dropbox/Soziologie/Frauen\ in\ der\ Wissenschaft/quantitative\ Erhebung/Arbeitsbereich\ Thomas/Berechnungen")

# daten einlesen -----------
df <- read.spss("Data/DATENSATZ_FiW.sav", use.value.labels=T, to.data.frame=T)
df_sav <- tbl_df(df)
df_sav <- df_sav %>%
  filter(., id %nin% c(27, 30, 37, 43, 45, 46, 91))
```

# Abbruchsintention nach Geschlecht
```{r unterbrecher}
# compute data to plot
pdata <- df_sav %>%
  with(., table(q_14, q_24)) %>% # create table with variables
  as.data.frame %>% # coerce to data.frame -> computes frequencies (Freq)
  group_by(q_24) %>% # group by categorial variable
  mutate(p = Freq/sum(Freq)) %>% # compute grouped percentage
  rename(., unterbrechung = q_14, Geschlecht = q_24)

plot1 <- ggplot(pdata, aes(unterbrechung, p, fill=Geschlecht)) 
plot1 + geom_bar(stat="identity", position="dodge") + theme_bw() + scale_y_continuous(labels = percent_format()) + scale_fill_brewer(palette="Paired") + labs(title="Abbruchsinention nach Geschlecht", y="Prozentanteile innerhalb Geschlecht", x="Darüber nachgedacht, Studium abzubrechen?") 

CrossTable(df_sav$q_14, df_sav$q_24, prop.r=F, prop.t=F, prop.chisq=F)
```

# Gründe für Abbrech-Gedanken
Die Prozentangaben sind nur für diejenigen berechnet, die angaben, übers Abbrechen nachgedacht zu haben.

```{r unterbrechungsgründe}

unterbrecher <- df_sav %>%
  filter(q_14 == "Ja") %>%
  select(., q_15_1:q_15_17)

d <- round(apply(unterbrecher, 2, function(col)sum(col=="Ja")/length(col))*100)

# setze "Names-Attribut" für barplot
attributes(d)$names <- c("Unzufriedenheit mit dem Studium", "Fehlende Aussicht auf institutionelle Einbindung an einer Universität", "Probleme bei der Finanzierung des Doktoratsstudiums", "Mangelnde Vereinbarkeit mit Berufstätigkeit", "Mangelnde Vereinbarkeit mit Betreuungspflichten", "Attraktive Arbeit gefunden", "Erwartungen an meine Leistungen nicht erfüllbar", "Interesse verloren", "Stillstand bei der Dissertation", "Schwierigkeiten eine/n BetreuerIn zu finden", "Nur nebenbei studiert", "Fehlende Unterstützung durch den/die BetreuerIn", "Keine befriedigenden Berufsaussichten mit dem Doktoratsabschluss", "Doktoratsstudium ist zu schwierig", "Doktoratsstudium als zeitliche Überbrückung gedacht", "Studienförderung läuft aus", "Kind bekommen bzw. werde ein Kind bekommen")

# margins setzen, damit beschriftung platz hat
par(mar=c(5, 18, 4, 2) + 0.1)
 
# plot
d[order(d, decreasing=F)] %>%
  barplot(., horiz=T, las=1, cex.names=.65, col="black")
title(main="Gründe für Unterbrechungsgedanken", xlab="Angaben in Prozent")

# die konkreten Zahlen nochmal übersichtlicher hier:
d[order(d, decreasing=T)]
```